export type M4Practice = {
  id: string;
  title: string;
  level: 'core' | 'extra';
  difficulty: 'Build' | 'Debug' | 'Stretch';
  contract: string;
  plan: string;
  boundary: string;
  hints: string[];
  starter: string;
  tests: string;
  solution: string;
  explanation: string;
  complexity: string;
};
export type M4Lesson = {
  id: number;
  title: string;
  short: string;
  intro: string;
  objectives: string[];
  concepts: { title: string; text: string }[];
  worked: string;
  walkthrough: { title: string; text: string }[];
  invariant: string;
  complexity: string;
  pitfalls: { title: string; text: string }[];
  checks: { question: string; answer: string }[];
  reflection: string;
  practices: M4Practice[];
  sources: { label: string; href: string }[];
};
