// Professional Studio: navy technical labs, cream workbook pages, sage learning evidence.
import { useEffect, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { ArrowLeft, ArrowRight, BookOpen, CheckCircle2, Download, FileText, Grid3X3, LockKeyhole, Plus, Code2 } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import CodeEditor from '@/components/CodeEditor';
import Module4Trace, { EfficiencyLab } from '@/components/Module4Trace';
import { useModuleProgress } from '@/contexts/ModuleProgressContext';
import { module4Lessons, module4Notice, module4Objectives, module4Steps, module4Sources, module4Core, module4Extra, practiceCode, downloadPractice } from '@/lib/module4';
import { useModule4Work, lessonReady4, readyForModule4, evidenceKeys4, requiredSteps, downloadWorkbook4, printWorkbook4 } from '@/lib/module4Progress';
import type { M4Lesson, M4Practice } from '@/lib/module4Types';
import './module3.css';
import './module4.css';

type WorkApi = ReturnType<typeof useModule4Work>;
function EvidenceField({ api, name, title, prompt }: { api: WorkApi; name: string; title: string; prompt: string }) {
  return <div className="m3-field"><label htmlFor={`m4-${name}`}>{title}</label><p id={`m4-${name}-help`}>{prompt}</p><Textarea id={`m4-${name}`} aria-describedby={`m4-${name}-help`} value={api.work.fields[name] || ''} onChange={e => api.field(name, e.target.value)} rows={5} placeholder="Write your reasoning, test evidence, and next action…" /><span className="m3-save" role="status">{api.error ? 'Not saved — download a backup before leaving.' : 'Saved in this browser as you type.'}</span></div>;
}
function ExportActions({ api }: { api: WorkApi }) {
  return <div className="m3-actions"><Button variant="outline" onClick={() => downloadWorkbook4(api.work)}><Download size={16} />Download learning record</Button><Button variant="outline" onClick={() => { if (!printWorkbook4(api.work)) toast.error('Allow pop-ups to open the print view.'); }}><FileText size={16} />Print / Save as PDF</Button></div>;
}
function PracticePanel({ practice: p, api }: { practice: M4Practice; api: WorkApi }) {
  const [editorOpen, setEditorOpen] = useState(false);
  const [hints, setHints] = useState(0);
  return <div className="m3-practice" data-practice={p.id}><span className="m3-chip">{p.level === 'core' ? 'CORE COMPANION' : 'OPTIONAL EXTRA'} / {p.difficulty.toUpperCase()} / {p.id}</span><h3>{p.title}</h3><p>{p.contract}</p><div className="m3-rule-grid"><article><h4>Plan before coding</h4><p>{p.plan}</p></article><article><h4>Boundary to investigate</h4><p>{p.boundary}</p></article></div>
    <div className="m4-hints"><Button variant="outline" disabled={hints >= p.hints.length} onClick={() => setHints(hints + 1)}>{hints === 0 ? 'Show first hint' : hints < p.hints.length ? 'Show next hint' : 'All hints revealed'}</Button>{p.hints.slice(0, hints).map((h, i) => <p key={i}><strong>Hint {i + 1}.</strong> {h}</p>)}</div>
    <p className="m3-muted">Starter assertions intentionally fail until you implement the function. The external Python editor is supplemental: this guide does not run or grade your code, save editor changes, or synchronize with Canvas. Copy your code before changing practice, resetting, or leaving.</p>
    {editorOpen ? <CodeEditor key={p.id} title={p.title} description="Python companion workspace — not an official submission" initialCode={practiceCode(p)} stdin="" height="520px" /> : <Button className="m3-primary" onClick={() => setEditorOpen(true)}><Code2 size={16} />Open Python practice editor</Button>}
    <details><summary>Read starter code and self-check tests</summary><pre className="m3-code"><code>{practiceCode(p)}</code></pre><Button variant="outline" onClick={() => downloadPractice(p)}><Download size={16} />Download starter .py</Button></details>
    <details className="m4-solution"><summary>Compare with a reference solution — after your attempt</summary><p>Use this to compare reasoning, not as evidence that your own implementation passed. More than one correct solution may satisfy the contract.</p><pre className="m3-code"><code>{p.solution}</code></pre><h4>Why this works</h4><p>{p.explanation}</p><h4>Time and space</h4><p>{p.complexity}</p><Button variant="outline" onClick={() => downloadPractice(p, true)}><Download size={16} />Download reference .py</Button></details>
    <label className="m3-checkbox"><Checkbox checked={api.work.practices.includes(p.id)} onCheckedChange={v => api.practice(p.id, v === true)} /><span>I attempted this practice and reviewed the provided tests.<small>{p.level === 'extra' ? 'Optional enrichment; not required for local module completion.' : 'Self-reported companion review; not an assessment grade.'}</small></span></label>
  </div>;
}
function LessonBody({ lesson, api }: { lesson: M4Lesson; api: WorkApi }) {
  const core = lesson.practices.filter(p => p.level === 'core');
  const [selected, setSelected] = useState(0);
  const reviewed = api.work.completed.includes(`lesson${lesson.id}`);
  return <>
    <section className="m3-paper"><div className="m3-eyebrow">01 / UNDERSTAND THE CONTRACT</div><h2>{lesson.short}</h2><div className="m4-objectives">{lesson.objectives.map((o, i) => <p key={o}><strong>0{i + 1}</strong>{o}</p>)}</div><div className="m3-concepts">{lesson.concepts.map(c => <article key={c.title}><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
    <Module4Trace key={lesson.id} lesson={lesson.id} />
    <section className="m3-paper"><div className="m3-eyebrow">02 / READ, TRACE, EXPLAIN</div><h2>A worked example, line by line.</h2><p>Read the output contract first. Predict the next state, then compare your reasoning with the walkthrough.</p><pre className="m3-code"><code>{lesson.worked}</code></pre><ol className="m4-walkthrough">{lesson.walkthrough.map((item, i) => <li key={item.title}><span>{i + 1}</span><div><h3>{item.title}</h3><p>{item.text}</p></div></li>)}</ol><div className="m3-invariant"><strong>Correctness anchor / loop invariant</strong><p>{lesson.invariant}</p></div><div className="m4-complexity"><h3>What does the improvement cost?</h3><p>{lesson.complexity}</p></div></section>
    <section className="m3-paper"><div className="m3-eyebrow">03 / CATCH THE FAILURE MODE</div><h2>Debug the assumption, not just the syntax.</h2><div className="m4-pitfalls">{lesson.pitfalls.map(p => <article key={p.title}><h3>{p.title}</h3><p>{p.text}</p></article>)}</div><h3>Predict before revealing</h3><p>These ungraded checks are thinking prompts. Explain your answer aloud or in Notes before opening the reasoning.</p>{lesson.checks.map((q, i) => <details className="m4-predict" key={q.question}><summary>Check {i + 1}: {q.question}</summary><p>{q.answer}</p></details>)}</section>
    <section className="m3-paper" id="practices"><div className="m3-eyebrow">04 / BUILD & TEST</div><h2>Two core companion practices.</h2><p>Attempt each problem, run the provided assertions in your Python environment, and add a case of your own. These activities prepare you to apply the ideas; they do not replace your assigned Canvas work.</p><div className="m3-practice-tabs" role="group" aria-label="Core practice selection">{core.map((p, i) => <Button key={p.id} variant={selected === i ? 'default' : 'outline'} aria-pressed={selected === i} onClick={() => setSelected(i)}>{api.work.practices.includes(p.id) && <CheckCircle2 size={14} />}Core practice {i + 1}</Button>)}</div><PracticePanel key={core[selected].id} practice={core[selected]} api={api} /><div className="m4-extra-banner"><Plus size={22} /><div><strong>Want more repetition or a bigger challenge?</strong><p>Three additional exercises extend this lesson, with progressive hints and explained solutions.</p><Link href="/module/4/practice">Open the extra-practice studio<ArrowRight size={16} /></Link></div></div></section>
    <section className="m3-paper"><div className="m3-eyebrow">05 / REFLECT & ACT</div><h2>Make the reasoning your own.</h2><EvidenceField api={api} name={`reflection${lesson.id}`} title={`Lesson ${lesson.id} reflection and action`} prompt={lesson.reflection} /><p className="m3-muted">Review the previous step, attempt both core companions, and enter your reflection to record this lesson review. Optional extras do not block progress.</p><Button className="m3-primary" disabled={reviewed || !lessonReady4(api.work, lesson.id)} onClick={() => { api.complete(`lesson${lesson.id}`); toast.success(`Lesson ${lesson.id} review saved`); }}>{reviewed ? <><CheckCircle2 size={16} />Lesson reviewed</> : `Mark Lesson ${lesson.id} Reviewed`}</Button></section>
  </>;
}
function ExtraStudio({ api }: { api: WorkApi }) {
  const [topic, setTopic] = useState('all');
  const [selected, setSelected] = useState(module4Extra[0].id);
  const filtered = module4Extra.filter(p => topic === 'all' || p.id.startsWith(`m4-l${topic}-`));
  const practice = filtered.find(p => p.id === selected) || filtered[0];
  return <><section className="m3-paper"><div className="m3-eyebrow">OPTIONAL / DELIBERATE PRACTICE</div><h2>Nine more ways to strengthen the pattern.</h2><p>Use <strong>Build</strong> to reinforce a routine, <strong>Debug</strong> to investigate a failure, and <strong>Stretch</strong> to transfer the idea. All nine are optional: choose the work that addresses your current gap, not just what is easiest to check off.</p><label className="m4-filter" htmlFor="m4-topic">Filter by topic<select id="m4-topic" value={topic} onChange={e => { setTopic(e.target.value); }}>{['all', '1', '2', '3'].map((v, i) => <option key={v} value={v}>{['All topics', 'Lesson 1 · Hash maps', 'Lesson 2 · Two pointers', 'Lesson 3 · Matrices'][i]}</option>)}</select></label><div className="m4-practice-grid" role="group" aria-label="Extra practice selection">{filtered.map(p => <button key={p.id} type="button" aria-pressed={practice.id === p.id} onClick={() => setSelected(p.id)}><span>{p.difficulty}{api.work.practices.includes(p.id) && <CheckCircle2 size={16} aria-label="Reviewed" />}</span><strong>{p.title}</strong></button>)}</div><p className="m3-muted">{module4Extra.filter(p => api.work.practices.includes(p.id)).length} of {module4Extra.length} optional exercises reviewed. Switching exercises closes the external editor; copy your code first.</p><PracticePanel key={practice.id} practice={practice} api={api} /></section>
    <section className="m3-paper"><div className="m3-eyebrow">OPTIONAL / INTEGRATION CHALLENGE</div><h2>Explain a grid-analysis pipeline.</h2><p>A monitoring dashboard receives a rectangular grid of integer sensor readings. Design a function that returns a frequency dictionary for all readings and a separate list containing the maximum value of each nonempty row. Return an empty dictionary and an empty list for an empty grid. Reject ragged rows and zero-width nonempty grids with ValueError. Do not change the input.</p><pre className="m3-code"><code>{'Input:  [[2, 2, 5], [5, 1, 2]]\nOutput: ({2: 3, 5: 2, 1: 1}, [5, 5])\n\nInput:  []\nOutput: ({}, [])\n\nInput:  [[1], [2, 3]]\nOutput: raises ValueError'}</code></pre><p>Sketch a single row-major pass that updates both results. Distinguish auxiliary memory from returned data. Explain why two pointers are not automatically helpful: there is no sorted pair-search contract here.</p><details><summary>Planning guidance</summary><p>Validate equal positive row lengths before processing. Start each row maximum from that row’s first value, not zero, so all-negative rows work. Increment one frequency count per cell. Visiting every cell is necessary to count every reading. For r rows, c columns, and u distinct values, the main pass takes average O(r × c) time with hash operations, and the returned structures hold O(u + r) entries.</p></details><EvidenceField api={api} name="capstone" title="Optional integration challenge record" prompt="Preserve your pseudocode or code, the empty and all-negative tests you ran, and your time/space explanation. This optional challenge does not affect completion." /><ExportActions api={api} /></section></>;
}
export default function Module4() {
  const [location] = useLocation();
  const api = useModule4Work();
  const { isModuleCompleted, isModuleUnlocked, markModuleComplete } = useModuleProgress();
  const step = module4Steps.find(s => s.path === location) || module4Steps[0];
  const index = module4Steps.indexOf(step);
  const lesson = module4Lessons.find(l => step.id === `lesson${l.id}`);
  const completed = isModuleCompleted(4);
  const eligible = readyForModule4(api.work) && isModuleUnlocked(4) && !api.error;
  const coreCount = module4Core.filter(p => api.work.practices.includes(p.id)).length;
  const extraCount = module4Extra.filter(p => api.work.practices.includes(p.id)).length;
  const pageTitle = lesson?.title || ({ overview: 'Optimization & Multidimensional Problems', practice: 'The extra-practice studio', discussion: 'Explain your engineering trade-offs.', completion: 'Keep the evidence. Carry the method.' }[step.id] || 'Module 4');
  const intro = lesson?.intro || ({ overview: 'Start with a correct solution. Then ask where the repeated work lives—and which assumption lets you remove it. Use hash maps, two pointers, and matrices to make better engineering decisions.', practice: 'Build fluency through focused repetition, debugging, and transfer. Choose a topic, make a prediction, and compare your reasoning—not just your output.', discussion: 'Translate a technical choice into a clear, defensible recommendation. Your best solution is the one that meets the contract and the real constraints.', completion: 'Preserve an efficiency comparison, a boundary test, and a debugging correction. Verify official work in Canvas separately from this personal learning record.' }[step.id]);
  useEffect(() => { window.scrollTo(0, 0); }, [location]);
  return <div className="m3-page m4-page" data-track={['discussion', 'completion'].includes(step.id) ? 'career' : 'technical'}><div className="m3-wrap">
    <div className="m3-breadcrumb"><Link href="/">Course home</Link><span>/</span><Link href="/module/4">Module 4</Link>{step.id !== 'overview' && <><span>/</span><span>{step.label}</span></>}</div>
    <header className="m3-header"><div className="m3-eyebrow">TECH460 / WEEK 04 {lesson && `/ LESSON 0${lesson.id}`}</div><h1>{pageTitle}</h1><p>{intro}</p><div className="m3-header-meta"><span><BookOpen size={16} />3 lessons</span><span><Grid3X3 size={16} />6 core companions</span><span><Plus size={16} />9 optional extras</span></div></header>
    <nav className="m3-local-nav" aria-label="Module 4 navigation"><div className="m3-bookmark"><strong>04</strong><span>OPTIMIZATION LAB</span></div>{module4Steps.map((s, i) => { const done = api.work.completed.includes(s.id) || (s.id === 'completion' && completed) || (s.id === 'practice' && extraCount === module4Extra.length); return <Link href={s.path} key={s.id} data-complete={done} aria-current={s.id === step.id ? 'page' : undefined}><span>{done ? <CheckCircle2 size={14} /> : String(i + 1).padStart(2, '0')}</span>{s.label}</Link>; })}<small className="m3-ribbon-caption">Contract → reason<br />→ test → improve</small></nav>
    {api.error && <div className="m3-warning" role="alert">{api.error}</div>}
    {!isModuleUnlocked(4) && <div className="m3-warning"><LockKeyhole size={18} /><p>Read and practice ahead if useful. Mark Module 3 complete before recording Module 4 completion. <Link href="/module/3/completion">Review Module 3 progress.</Link></p></div>}
    <aside className="m3-canvas"><strong>Companion learning; Canvas remains authoritative.</strong><p>{module4Notice}</p></aside>
    {step.id === 'overview' && <>
      <section className="m3-objective"><span>WEEK<br /><b>04</b></span><div><h2>Make each operation earn its place.</h2><p>The course-map outcome is to explain correct, efficient trade-offs. This companion module develops four practical goals:</p><ol className="m4-goals">{module4Objectives.map(o => <li key={o}>{o}</li>)}</ol></div></section>
      <section className="m3-paper"><div className="m3-eyebrow">YOUR LEARNING PATH</div><h2>Three techniques. One decision process.</h2><p>Module 3 taught you to trace loops. This week, reuse those traces to locate redundant work. Learn each technique’s assumptions before applying it; fewer lines of code do not automatically mean less work.</p>{module4Lessons.map(l => <article className="m3-chapter" key={l.id}><div className="m3-chapter-number">0{l.id}</div><div><h3><Link href={`/module/4/lesson${l.id}`}>{l.title}<ArrowRight size={18} /></Link></h3><p>{l.short} · 2 core companions + 3 optional extras</p><ol>{l.practices.filter(p => p.level === 'core').map(p => <li key={p.id}>{p.title}</li>)}</ol></div></article>)}</section>
      <EfficiencyLab />
      <section className="m3-paper"><div className="m3-eyebrow">CHOOSE A STRATEGY</div><h2>Start with the constraint that matters.</h2><div className="m4-table-wrap"><table className="m4-table"><caption>Strategy selection guide</caption><thead><tr><th>When the task asks…</th><th>Consider…</th><th>Check first…</th></tr></thead><tbody><tr><td>Have I seen this value? How often?</td><td>A set or dictionary</td><td>Hashable keys, duplicate policy, and extra memory</td></tr><tr><td>Does a sorted sequence contain a target pair?</td><td>Opposing pointers</td><td>Sorted order and whether original indices must be retained</td></tr><tr><td>Can I compact or merge sequences?</td><td>Read/write or merge pointers</td><td>Mutation permissions and what the returned prefix means</td></tr><tr><td>How do cells or neighbors relate?</td><td>Row/column traversal</td><td>Rectangular shape, both bounds, and update order</td></tr></tbody></table></div><p>Use a simple correct baseline when the constraints do not justify an optimization. A matrix with r rows and c columns contains r × c cells: nested loops over its cells are O(r × c), not automatically O(n²) if n means total cells.</p></section>
      <section className="m3-paper"><div className="m3-eyebrow">WHAT TO KEEP</div><h2>A record another engineer can follow.</h2><div className="m3-rule-grid"><article><h3>In this companion</h3><p>Review the overview, three lessons and six core practices. Write lesson reflections and a strategy discussion draft. Save three evidence entries on the completion page. The nine extras and integration challenge are optional.</p></article><article><h3>In Canvas</h3><p>Read the actual Module 4 overview and requirements. Launch each assigned lesson and activity from its individual Canvas link. Follow the official discussion and feedback instructions there. This guide does not know your assigned points or due dates.</p></article></div><p className="m3-muted">Notes and progress are local to this browser. Keep downloaded backups; neither your instructor nor Canvas receives these drafts automatically.</p><Button className="m3-primary" disabled={api.work.completed.includes('overview')} onClick={() => api.complete('overview')}>{api.work.completed.includes('overview') ? 'Overview reviewed' : 'Mark Overview Reviewed'}</Button></section>
    </>}
    {lesson && <LessonBody key={lesson.id} lesson={lesson} api={api} />}
    {step.id === 'practice' && <ExtraStudio api={api} />}
    {step.id === 'discussion' && <>
      <section className="m3-paper"><div className="m3-eyebrow">COMPANION DISCUSSION / NOT THE OFFICIAL CANVAS PROMPT</div><h2>“Faster” is not a complete recommendation.</h2><p>As a soon-to-graduate technology professional, you need to explain how a decision changes correctness, resource use, and maintainability. Saying “I used a dictionary because it is faster” omits the input assumptions, memory cost, and evidence that your output is still correct.</p><p>Use a Module 4 exercise to prepare a short engineering recommendation. Compare a baseline with an alternative, explain the contract both must satisfy, and identify a constraint that could change your decision. Distinguish an operation-count model from an actual timing experiment. If you did not measure elapsed time, do not present a speedup as measured.</p><blockquote>Suggested structure: Given [input and constraints], I chose [approach] over [baseline]. The correctness argument is [invariant or elimination rule]. The time/space trade-off is [analysis]. My evidence is [specific test]. I would reconsider if [changed constraint].</blockquote><p>Adapt this draft only where it fits the official Module 4 discussion. Check Canvas for its actual topic, length, reply expectations, and due date.</p></section>
      <section className="m3-paper"><h2>Build a defensible technical explanation.</h2><div className="m3-concepts"><article><h3>Name the contract</h3><p>Does the task return values or original indices? One pair or all pairs? Is the input sorted? May it be mutated? These details can invalidate an otherwise elegant solution.</p></article><article><h3>Show one piece of evidence</h3><p>Include exact test inputs and expected/actual outputs. Explain why a duplicate, empty collection, unsorted input, or rectangular grid challenges an assumption.</p></article><article><h3>State the cost honestly</h3><p>Name n, r, or c before using Big O. Include sorting, temporary copies, and result storage. Say “average” when a hash-table claim depends on average-case behavior.</p></article><article><h3>Ask a useful peer question</h3><p>When Canvas calls for replies, ask which input property justifies the optimization, or offer a counterexample that tests its limits. Challenge the assumption respectfully, not the person.</p></article></div><EvidenceField api={api} name="strategy" title="Engineering trade-offs discussion draft" prompt="Explain your contract, baseline, chosen approach, correctness argument, time/space costs, one exact test, and a condition that would change your recommendation. Post the required response in Canvas yourself." /><ExportActions api={api} /><p className="m3-muted">Review all three lessons and enter a draft before recording this step.</p><Button className="m3-primary" disabled={api.work.completed.includes('discussion') || !api.work.fields.strategy?.trim() || ![1, 2, 3].every(n => api.work.completed.includes(`lesson${n}`))} onClick={() => api.complete('discussion')}>{api.work.completed.includes('discussion') ? 'Discussion draft reviewed' : 'Mark Discussion Draft Reviewed'}</Button></section>
    </>}
    {step.id === 'completion' && <>
      <section className="m3-paper"><div className="m3-eyebrow">PERSONAL PROGRESS / NOT A VERIFIED GRADE</div><h2>{completed ? 'Module 4 marked complete.' : 'Review your Module 4 record.'}</h2><div className="m3-completion-stats"><strong>{coreCount}<small>/ 6 core companions</small></strong><strong>{extraCount}<small>/ 9 optional extras</small></strong><strong>{evidenceKeys4.filter(k => api.work.fields[k]?.trim()).length}<small>/ 3 evidence entries</small></strong></div><div className="m3-status-list">{module4Steps.filter(s => requiredSteps.includes(s.id)).map(s => <Link key={s.id} href={s.path}><CheckCircle2 size={18} className={api.work.completed.includes(s.id) ? 'm3-done' : ''} />{s.label}<span>{api.work.completed.includes(s.id) ? 'Reviewed' : 'Needs review'}</span></Link>)}</div><p className="m3-muted">Review markers are self-reported learning milestones, not automated code verification. Optional extra practice is never required to complete this module.</p></section>
      <section className="m3-paper"><div className="m3-eyebrow">YOUR EVIDENCE / THREE CLEAR EXPLANATIONS</div><h2>Show what changed—and why it is sound.</h2><EvidenceField api={api} name="tradeoff" title="1. Before / after trade-off" prompt="Identify your exercise. Define the input size, compare baseline and revised time/space costs, list the assumptions, and explain why the revised approach remains correct. State whether any speed claim is modeled or measured." /><EvidenceField api={api} name="boundary" title="2. Boundary-test evidence" prompt="Record exact input, expected result, actual result, and what the test protects against. Choose a duplicate, empty input, original-index constraint, rectangular matrix, or another meaningful edge case." /><EvidenceField api={api} name="correction" title="3. Debugging correction" prompt="Describe a faulty assumption or line of code, the observed symptom, your correction, and the regression test. Explain why your correction fixes the cause rather than just this example." /><ExportActions api={api} /><p className="m3-muted">The export includes your reflections, drafts, and review checklist. Code edited inside Coddy is not included; save your .py files separately.</p></section>
      <section className="m3-paper"><h2>Check the authoritative course requirements.</h2><p>Open Canvas Module 4 and verify every assigned lesson, activity, discussion, and any feedback or survey requirement listed there. Use the individual Canvas links for all official CodeSignal work. This checkbox records your review only; it does not confirm grades or submissions.</p><label className="m3-checkbox"><Checkbox checked={api.work.canvasChecked} onCheckedChange={v => api.update(old => ({ ...old, canvasChecked: v === true }))} /><span>I checked the official Module 4 requirements and my assigned work in Canvas.</span></label><EvidenceField api={api} name="pulse" title="Personal pulse reflection (optional)" prompt="Which technique can you now explain without the solution? Which gap will you practice before timed work in Module 5? This private reflection is not sent to your instructor." /></section>
      <section className="m3-finish"><div className="m3-eyebrow">NEXT / WEEK 05</div><h2>Correct first. Efficient with evidence.</h2><p>Carry your tested patterns into Timed Readiness & Efficient Problem Solving. Under time pressure, state the contract, implement a reliable baseline, test a boundary, then optimize only where it matters. Module 5 remains a coming-soon page.</p><div className="m3-actions"><Button className="m3-primary" disabled={!eligible || completed} onClick={() => { if (eligible) { markModuleComplete(4); toast.success('Module 4 completion saved in this browser'); } }}>{completed ? <><CheckCircle2 size={16} />Module 4 Completed</> : 'Mark Module 4 Complete'}</Button>{completed && <Link href="/module/5" className="m3-text-link">Preview Module 5<ArrowRight size={16} /></Link>}</div>{!completed && <p className="m3-muted">Requires Module 3 completion, overview + three lesson reviews + discussion review, six core companion attempts, three lesson reflections, discussion draft, three evidence entries, and Canvas-work confirmation. Entries are checked for presence, not graded for quality.</p>}</section>
    </>}
    <section className="m3-references"><h2>Reference desk</h2><p>Scope: the instructor-supplied Week 4 course map. Detailed lesson objectives and exercises on these pages are companion material. These technical references support the explanations; they are not alternate official activity-launch links.</p>{(lesson?.sources || module4Sources).map(s => <a href={s.href} key={s.href} target="_blank" rel="noreferrer">{s.label}</a>)}</section>
    <footer className="m3-footer">{index > 0 ? <Link href={module4Steps[index - 1].path}><ArrowLeft size={16} />{module4Steps[index - 1].label}</Link> : <Link href="/module/3/completion"><ArrowLeft size={16} />Module 3</Link>}{index < module4Steps.length - 1 ? <Link href={module4Steps[index + 1].path}>Next: {module4Steps[index + 1].label}<ArrowRight size={16} /></Link> : <Link href="/">Course roadmap<ArrowRight size={16} /></Link>}</footer>
  </div></div>;
}
