// Professional Studio: editorial lesson chapters, navy/sage evidence panels, progressive practice disclosure.
import { useEffect, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { ArrowRight, ArrowLeft, CheckCircle2, BookOpen, Download, FileText, Repeat, MessageSquare, LockKeyhole } from 'lucide-react';
import { toast } from 'sonner';
import CodeEditor from '@/components/CodeEditor';
import Module3Trace from '@/components/Module3Trace';
import { useModuleProgress } from '@/contexts/ModuleProgressContext';
import { module3Lessons, module3Objective, module3Notice, module3Sources, starterCode, type Lesson } from '@/lib/module3';
import { useModule3Work, hasEvidence, readyForModule3, downloadWorkbook, printWorkbook, evidenceKeys, evidenceLabels } from '@/lib/module3Progress';
import './module3.css';

const steps = [{ id: 'overview', path: '/module/3', label: 'Overview' }, ...module3Lessons.map(l => ({ id: `lesson${l.id}`, path: `/module/3/lesson${l.id}`, label: `Lesson ${l.id}` })), { id: 'discussion', path: '/module/3/discussion', label: 'Discussion' }, { id: 'completion', path: '/module/3/completion', label: 'Completion' }];
type WorkApi = ReturnType<typeof useModule3Work>;

function EvidenceField({ api, name, title, prompt }: { api: WorkApi; name: string; title: string; prompt: string }) {
  return <div className="m3-field"><label htmlFor={`m3-${name}`}>{title}</label><p id={`m3-${name}-help`}>{prompt}</p><Textarea id={`m3-${name}`} aria-describedby={`m3-${name}-help`} value={api.work.fields[name] || ''} onChange={e => api.field(name, e.target.value)} rows={5} placeholder="Write your own explanation and evidence…" /><span className="m3-save" role="status">{api.error ? 'Not saved — download a backup.' : 'Saved in this browser as you type.'}</span></div>;
}
function ExportActions({ api }: { api: WorkApi }) {
  return <div className="m3-actions"><Button variant="outline" onClick={() => downloadWorkbook(api.work)}><Download size={16} />Download learning record</Button><Button variant="outline" onClick={() => { if (!printWorkbook(api.work)) toast.error('Allow pop-ups to open the print view.'); }}><FileText size={16} />Print / Save as PDF</Button></div>;
}
function LessonBody({ lesson, api }: { lesson: Lesson; api: WorkApi }) {
  const [selected, setSelected] = useState(0);
  const [editorOpen, setEditorOpen] = useState(false);
  const [answerOpen, setAnswerOpen] = useState(false);
  const p = lesson.practices[selected];
  const fieldName = `reflection${lesson.id}`;
  const done = lesson.practices.every(item => api.work.practices.includes(item.id));
  const prior = lesson.id === 1 ? 'overview' : `lesson${lesson.id - 1}`;
  const canComplete = done && Boolean(api.work.fields[fieldName]?.trim()) && api.work.completed.includes(prior);
  return <>
    <section className="m3-paper"><div className="m3-eyebrow">01 / UNDERSTAND</div><h2>Choose the rule. Then choose the loop.</h2><div className="m3-concepts">{lesson.concepts.map(c => <article key={c.title}><h3>{c.title}</h3><p>{c.text}</p></article>)}</div></section>
    <Module3Trace key={lesson.id} kind={lesson.id === 1 ? 'opposite' : lesson.id === 2 ? 'nested' : 'simulation'} />
    <section className="m3-paper"><div className="m3-eyebrow">02 / READ & TRACE</div><h2>A worked companion example</h2><p>Read the assertions as an input–output contract. Trace the example once by hand before running it.</p><pre className="m3-code"><code>{lesson.worked}</code></pre><div className="m3-invariant"><strong>Loop invariant</strong><p>{lesson.invariant}</p></div><h3>Debugging checkpoint</h3><p>{lesson.debug}</p><div className="m3-check"><h3>Predict before revealing</h3><p>{lesson.check.question}</p><Button variant="outline" onClick={() => setAnswerOpen(!answerOpen)} aria-expanded={answerOpen}>{answerOpen ? 'Hide explanation' : 'Reveal explanation'}</Button>{answerOpen && <p role="status">{lesson.check.answer}</p>}</div></section>
    <section className="m3-paper" id="practices"><div className="m3-eyebrow">03 / APPLY</div><h2>Your practice studio</h2><p>Select an activity. Read its companion contract, sketch the loop, and test your implementation. The checkbox records your own review; it does not check or submit CodeSignal work.</p><div className="m3-practice-tabs" role="group" aria-label="Select a practice">{lesson.practices.map((item, i) => <Button key={item.id} variant={selected === i ? 'default' : 'outline'} aria-pressed={selected === i} onClick={() => { setSelected(i); setEditorOpen(false); }}>{api.work.practices.includes(item.id) && <CheckCircle2 size={14} />}Practice {i + 1}</Button>)}</div>
      <div className="m3-practice" key={p.id}><span className="m3-chip">COMPANION EXERCISE · {selected + 1} / {lesson.practices.length}</span><h3>{p.title}</h3><p>{p.contract}</p><div className="m3-rule-grid"><article><h4>Plan the traversal</h4><p>{p.plan}</p></article><article><h4>Test the boundary</h4><p>{p.boundary}</p></article></div><details><summary>Show a planning hint</summary><p>{p.hint}</p></details>
      <p className="m3-muted">The embedded editor is supplemental practice. It does not synchronize with Canvas, and code inside it is not saved by this guide. Copy your work before resetting or switching activities. Starter assertions fail until you implement the function.</p>
      {editorOpen ? <CodeEditor key={p.id} title={`Lesson ${lesson.id} · Practice ${selected + 1}`} description="Companion Python workspace — not a graded submission" initialCode={starterCode(p)} stdin="" height="520px" /> : <Button className="m3-primary" onClick={() => setEditorOpen(true)}>Open Python practice editor<ArrowRight size={16} /></Button>}
      <details><summary>View starter code and test cases as text</summary><pre className="m3-code"><code>{starterCode(p)}</code></pre></details>
      <label className="m3-checkbox"><Checkbox checked={api.work.practices.includes(p.id)} onCheckedChange={value => api.practice(p.id, value === true)} /><span>I attempted this companion practice and reviewed its test results.</span></label></div>
    </section>
    <section className="m3-paper"><div className="m3-eyebrow">04 / EXPLAIN</div><h2>Keep evidence, not just answers.</h2><EvidenceField api={api} name={fieldName} title={`Lesson ${lesson.id} reflection`} prompt={lesson.id === 1 ? 'Which pairing rule did you use? Explain the index bounds and what happens for odd-length input.' : lesson.id === 2 ? 'Explain your candidate traversal and duplicate policy. When would break lose valid results?' : 'Describe the state, update rule, and termination condition. Record one transition that you checked by hand.'} />
    <p className="m3-muted">To mark this lesson reviewed, finish the previous step, review all {lesson.practices.length} companions, and enter your reflection. This is a local learning checklist, not a grade.</p><Button className="m3-primary" disabled={!canComplete || api.work.completed.includes(`lesson${lesson.id}`)} onClick={() => { api.complete(`lesson${lesson.id}`); toast.success(`Lesson ${lesson.id} review saved`); }}>{api.work.completed.includes(`lesson${lesson.id}`) ? <><CheckCircle2 size={16} />Lesson reviewed</> : `Mark Lesson ${lesson.id} Reviewed`}</Button></section>
  </>;
}

export default function Module3() {
  const [location] = useLocation();
  const api = useModule3Work();
  const { isModuleCompleted, isModuleUnlocked, markModuleComplete } = useModuleProgress();
  const step = steps.find(s => s.path === location) || steps[0];
  const stepIndex = steps.indexOf(step);
  const lesson = module3Lessons.find(l => step.id === `lesson${l.id}`);
  const completed = isModuleCompleted(3);
  const eligible = readyForModule3(api.work) && isModuleUnlocked(3) && !api.error;
  useEffect(() => { window.scrollTo(0, 0); }, [location]);
  const pageTitle = lesson?.title || (step.id === 'discussion' ? 'Your Personal Brand' : step.id === 'completion' ? 'Bring your learning together.' : 'Looping & Interview Implementation');
  return <div className="m3-page" data-track={step.id === 'discussion' || step.id === 'completion' ? 'career' : 'technical'}><div className="m3-wrap">
    <div className="m3-breadcrumb"><Link href="/">Course home</Link><span>/</span><Link href="/module/3">Module 3</Link>{step.id !== 'overview' && <><span>/</span><span>{step.label}</span></>}</div>
    <header className="m3-header"><div className="m3-eyebrow">TECH460 / WEEK 03 {lesson && `/ LESSON 0${lesson.id}`}</div><h1>{pageTitle}</h1><p>{lesson?.intro || (step.id === 'discussion' ? 'Make your professional strengths visible through specific, truthful evidence. Connect how you solve a problem to the value you offer a team.' : step.id === 'completion' ? 'Review your practice, preserve your reasoning, and verify your assigned work in Canvas before moving on.' : 'Move from writing a loop to explaining why it works. Pair elements, compare collections, and simulate changing states—one deliberate iteration at a time.')}</p><div className="m3-header-meta"><span><BookOpen size={16} />3 lessons</span><span><Repeat size={16} />10 practice companions</span><span><FileText size={16} />3 evidence artifacts</span></div></header>
    <nav className="m3-local-nav" aria-label="Module 3 navigation"><div className="m3-bookmark"><strong>03</strong><span>MODULE JOURNAL</span></div>{steps.map((s, index) => <Link href={s.path} key={s.id} data-complete={api.work.completed.includes(s.id) || (s.id === 'completion' && completed)} aria-current={step.id === s.id ? 'page' : undefined}><span>{api.work.completed.includes(s.id) || (s.id === 'completion' && completed) ? <CheckCircle2 size={14} /> : String(index + 1).padStart(2, '0')}</span>{s.label}</Link>)}<small className="m3-ribbon-caption">Read → practice<br />→ preserve evidence</small></nav>
    {api.error && <div className="m3-warning" role="alert">{api.error}</div>}
    {!isModuleUnlocked(3) && <div className="m3-warning"><LockKeyhole size={18} /><p>You may read ahead. Mark Module 2 complete before recording Module 3 completion. <Link href="/module/2/completion">Review Module 2 progress.</Link></p></div>}
    <aside className="m3-canvas"><strong>Canvas is your assignment hub.</strong><p>{module3Notice}</p></aside>

    {step.id === 'overview' && <>
      <section className="m3-objective"><span>OBJECTIVE<br /><b>03</b></span><div><h2>Repetition with a reason.</h2><p>{module3Objective}</p></div></section>
      <section className="m3-paper"><div className="m3-eyebrow">YOUR LEARNING PATH</div><h2>Three patterns. One reliable process.</h2><p>First state the contract. Then predict, implement, test, and explain. Module 2 supplied the building blocks; this week turns them into repeatable problem-solving habits.</p>{module3Lessons.map(l => <article className="m3-chapter" key={l.id}><div className="m3-chapter-number">0{l.id}</div><div><h3><Link href={`/module/3/lesson${l.id}`}>{l.title}<ArrowRight size={18} /></Link></h3><p>{l.short} · {l.practices.length} practices</p><ol>{l.practices.map(p => <li key={p.id}>{p.title}</li>)}</ol></div></article>)}</section>
      <section className="m3-paper"><div className="m3-eyebrow">CAREER + CODING</div><h2>Turn your process into professional evidence.</h2><p>The <Link href="/module/3/discussion">Your Personal Brand discussion</Link> connects your technical work with a credible professional story. The weekly evidence record asks you to preserve one loop invariant, one boundary test, and one debugging correction.</p><div className="m3-rule-grid"><article><h3>Complete in Canvas</h3><p>Open each assigned lesson and practice through its individual Module 3 link. Complete the discussion and Module 3 Pulse Survey there. Use Canvas for current instructions, due dates, and points.</p></article><article><h3>Retain in this guide</h3><p>Keep reflections and a concise learning record. Browser progress is self-reported and does not confirm submissions or grades. Download a backup before clearing browser data or resetting the course.</p></article></div><Button className="m3-primary" disabled={api.work.completed.includes('overview')} onClick={() => api.complete('overview')}>{api.work.completed.includes('overview') ? 'Overview reviewed' : 'Mark Overview Reviewed'}</Button></section>
    </>}

    {lesson && <LessonBody key={lesson.id} lesson={lesson} api={api} />}

    {step.id === 'discussion' && <>
      <section className="m3-paper"><div className="m3-eyebrow">DISCUSSION / YOUR PERSONAL BRAND</div><h2>Show the evidence behind your strengths.</h2><p>Hello TECH460 students, a personal brand is not a list of impressive adjectives. It is the consistent professional impression supported by your work, your decisions, and the way you communicate. As you approach graduation, your challenge is to explain not only what you know, but how someone else can see it in action.</p><p>This week’s loop practice gives you concrete material. Explaining an invariant demonstrates careful reasoning. A boundary test shows that you anticipate failure conditions. A debugging correction shows how you investigate and improve. Use one of these artifacts to replace a broad claim such as “I am a strong problem solver” with a specific account of what you did and learned.</p><blockquote>Suggested drafting frame: I am developing as a [role] who helps [audience] achieve [outcome] through [skills or working habits]. Evidence of this is [specific project, test, or improvement].</blockquote><p>This framing is a companion writing guide, not an additional grading rubric. Follow the official discussion prompt, length, reply requirements, and deadline in Canvas.</p></section>
      <section className="m3-paper"><h2>Build your discussion draft</h2><div className="m3-concepts"><article><h3>State your direction</h3><p>Identify a target role or professional area. Name two strengths you can substantiate, rather than certifications or experience you do not yet have.</p></article><article><h3>Connect one artifact</h3><p>Describe the problem, your contribution, the evidence, and what it demonstrates. A small, well-explained debugging correction can be more informative than a broad claim of expertise.</p></article><article><h3>Name a growth commitment</h3><p>Choose one professional habit to develop, such as clear documentation or communicating uncertainty. State a specific action and how you will check your progress.</p></article><article><h3>Respond constructively</h3><p>When replying according to Canvas instructions, identify the strength you can see in a peer’s evidence and ask a question that helps make the claim more precise. Do not publish private employer or client details.</p></article></div><EvidenceField api={api} name="brand" title="Personal brand discussion draft" prompt="Connect your professional direction, two evidence-based strengths, one Module 3 example, and one growth commitment. This saves a draft only; post it in Canvas yourself." /><ExportActions api={api} /><p className="m3-muted">Review Lessons 1–3 and enter a draft before marking this step reviewed.</p><Button className="m3-primary" disabled={!api.work.fields.brand?.trim() || !['lesson1', 'lesson2', 'lesson3'].every(id => api.work.completed.includes(id)) || api.work.completed.includes('discussion')} onClick={() => api.complete('discussion')}>{api.work.completed.includes('discussion') ? 'Discussion draft reviewed' : 'Mark Discussion Draft Reviewed'}</Button></section>
    </>}

    {step.id === 'completion' && <>
      <section className="m3-paper"><div className="m3-eyebrow">PERSONAL REVIEW / NOT A CANVAS GRADE</div><h2>{completed ? 'Module 3 marked complete.' : 'Check your learning record.'}</h2><div className="m3-completion-stats"><strong>{api.work.practices.length}<small>/ 10 companions reviewed</small></strong><strong>{evidenceKeys.filter(k => api.work.fields[k]?.trim()).length}<small>/ 3 evidence artifacts</small></strong></div><div className="m3-status-list">{steps.filter(s => s.id !== 'completion').map(s => <Link href={s.path} key={s.id}><CheckCircle2 size={18} className={api.work.completed.includes(s.id) ? 'm3-done' : ''} />{s.label}<span>{api.work.completed.includes(s.id) ? 'Reviewed' : 'Needs review'}</span></Link>)}</div></section>
      <section className="m3-paper"><div className="m3-eyebrow">WEEKLY COMPLETION GUIDANCE</div><h2>Preserve three pieces of reasoning.</h2><p>Complete the simple-loop, nested-loop, and simulation practice sets. Preserve at least one explanation of a loop invariant, one boundary test, and one debugging correction.</p><EvidenceField api={api} name="invariant" title="1. Loop invariant" prompt="Identify the exercise and state what remains true before each iteration. Explain initialization, preservation, and what the invariant tells you at termination." /><EvidenceField api={api} name="boundary" title="2. Boundary test" prompt="Record the exercise, exact input, expected output, actual output, and why that boundary matters (for example, empty input or an unpaired last element)." /><EvidenceField api={api} name="debugging" title="3. Debugging correction" prompt="Record the symptom, the faulty line or rule, the correction, and a regression test. Explain why the corrected loop now makes progress or respects its bounds." /><ExportActions api={api} /></section>
      <section className="m3-paper"><h2>Verify your assigned work in Canvas</h2><p>The checklist below records your review only. Complete each lesson and practice through its individual Canvas link, then check your submitted work there.</p>{module3Lessons.map(l => <details className="m3-checklist-group" key={l.id}><summary>Lesson {l.id} · {l.practices.length} practices</summary>{l.practices.map(p => <label className="m3-checkbox" key={p.id}><Checkbox checked={api.work.practices.includes(p.id)} onCheckedChange={v => api.practice(p.id, v === true)} /><span>{p.title} <small>Companion review only</small></span></label>)}</details>)}<h3>Module 3 Pulse Survey</h3><p>Open <strong>Module 3 Pulse Survey</strong> in Canvas and submit your feedback there. The optional reflection below is private to this browser; it is not sent to your instructor.</p><EvidenceField api={api} name="pulse" title="Personal pulse reflection (optional)" prompt="Which loop pattern feels most reliable now? What do you want to revisit before Module 4?" /><label className="m3-checkbox"><Checkbox checked={api.work.canvasChecked} onCheckedChange={v => api.update(old => ({ ...old, canvasChecked: v === true }))} /><span>I checked my assigned lessons, ten graded practices, Your Personal Brand discussion, and Module 3 Pulse Survey in Canvas.</span></label></section>
      <section className="m3-finish"><div className="m3-eyebrow">NEXT / MODULE 4</div><h2>From correct to efficient.</h2><p>Carry your loop traces into Optimization & Multidimensional Problems. You will use your current approach as a baseline when considering hash maps, pointers, matrices, and efficiency trade-offs.</p><p>{!hasEvidence(api.work) ? 'Add all three evidence artifacts before recording completion.' : 'Your three evidence fields are present. Review them for accuracy; this guide does not grade their quality.'}</p><div className="m3-actions"><Button className="m3-primary" disabled={!eligible || completed} onClick={() => { if (eligible) { markModuleComplete(3); toast.success('Module 3 completion saved in this browser'); } }}>{completed ? <><CheckCircle2 size={16} />Module 3 Completed</> : 'Mark Module 3 Complete'}</Button>{completed && <Link className="m3-text-link" href="/module/4">Continue to Module 4<ArrowRight size={16} /></Link>}</div>{!completed && <p className="m3-muted">Completion requires Module 2 completion, all five review steps, ten companion reviews, three evidence entries, and your Canvas-work confirmation. This records personal progress, not an official badge or assessment result.</p>}</section>
    </>}

    <section className="m3-references"><h2>Reference desk</h2><p>Curriculum titles and objective: instructor-supplied Module 3 outline. Technical references support the companion explanations; they are not alternate activity-launch links.</p>{module3Sources.map(source => <a key={source.href} href={source.href} target="_blank" rel="noreferrer">{source.label}</a>)}</section>
    <footer className="m3-footer">{stepIndex > 0 ? <Link href={steps[stepIndex - 1].path}><ArrowLeft size={16} />{steps[stepIndex - 1].label}</Link> : <Link href="/module/2/completion"><ArrowLeft size={16} />Module 2</Link>}{stepIndex < steps.length - 1 ? <Link href={steps[stepIndex + 1].path}>Next: {steps[stepIndex + 1].label}<ArrowRight size={16} /></Link> : <Link href="/">Course roadmap<ArrowRight size={16} /></Link>}</footer>
  </div></div>;
}
